version: "3"
services:
  nginx:
    command: nginx-debug -g 'daemon off;'
    image: nginx:alpine
    volumes:
      - ./config/nginx/nginx-cache-control-headers.conf:/etc/nginx/nginx-cache-control-headers.conf:ro
      - ./config/nginx/nginx-security-headers.conf:/etc/nginx/nginx-security-headers.conf:ro
      - ./config/nginx/nginx-ssl-options.conf:/etc/nginx/nginx-ssl-options.conf:ro
      - ./config/nginx/nginx-deny-invisible-file-access.conf:/etc/nginx/nginx-deny-invisible-file-access.conf:ro
      - ./config/nginx/nginx-proxy-to-hubspot-articles.inc:/etc/nginx/nginx-proxy-to-hubspot-articles.inc:ro
      - ./config/nginx/nginx-proxy-to-local.conf:/etc/nginx/nginx-proxy-to-local.conf:ro
      - ./config/nginx/nginx-proxy-to-hubspot-ascent-blog.conf:/etc/nginx/nginx-proxy-to-hubspot-ascent-blog.conf:ro
      - ./config/nginx/localhost.crt:/etc/nginx/localhost.crt:ro
      - ./config/nginx/rootCA.pem:/etc/nginx/rootca.pem:ro
      - ./config/nginx/localhost.key:/etc/nginx/localhost.key:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443

